Feature/check usernames and emails#8
eignatik/petpool-ui pull request #14
Opened 2019-08-11 12:16 UTC by githelga

#8 Sign Up from validation

All items are done.
Checking of uniqueness is fake and always true

2019-08-11 13:11 UTC, eignatik requested changes

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +  checkElementIsNotOnlyAlphabet(value) {
Лучше не использовать двойные отрицания - один в названии метода, другой внутри. Лучше сразу назвать метод правильно, например,  `hasOnlyAlphabetInput(username) {...}` это будет более читаемо.

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +  validateProperty(name, value) {
Думаю, что валидация занимает очень много места, надо ее выносить в отдельный util класс. 
Скорее всего что-то можно будет даже переиспользовать в других компонентах

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +    let t = [this.checkElementIsEmpty(this.state.person.userName), this.checkElementIsEmpty(this.state.person.email),
Что такое `t`? 
Стоит придерживаться информативного именования переменных, у нас нет необходимости укладывать код программы в несколько килобайт, потому мы можем позволить себе более длинные названия переменных :)

2019-08-11 13:11 UTC, eignatik commented on src/constants/index.js
> +export const COUNTRIES = [
Название файла index.js не самое очевидное название. Стоит его переименовать во что-то более отражающие его смысл - Constants, whatever else

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +      && !/^([A-Za-zА-Яа-я0-9])([A-Za-zА-Яа-я0-9_\.]+)([A-Za-zА-Яа-я0-9])$/.test(value);
логин пользователя не может содержать кириллицы, только латинский алфавит
Только имя и фамилия могут быть и на латинице, и на кириллице   https://app.zenhub.com/workspaces/petpool-5d488ae4ca85b60001ddc8fa/issues/eignatik/petpool-ui/8

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +      case 'userName':
Я думаю, что стоит сделать константы для названий property, потому что есть уже как минимум 3-4 кейса, где это можно переиспользовать. 
Создание каждый раз строковых литералов очень errors prone, это ухудшает качество кода и его поддерживаемость.
Можно вынести это все в константы, и даже переиспользовать при рендеринге формы.

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +  handleChange(e, d) {
нужно более информативное название для каждого аргумента функции - `e`, `d` - непонятно

2019-08-11 13:11 UTC, eignatik commented on src/components/signup/SignUp.js
> +  handleBlur(e) {
`e` - event?
Нужно или писать документацию к методу, или же называть аргументы более длинными словами

2019-08-11 13:11 UTC, eignatik commented on src/constants/index.js
> +export const COUNTRIES = [
Так же думаю, что вместо собственного создания такой константы, можно использовать готовую библиотеку. Например, вот такую: https://www.npmjs.com/package/countries-list
Но можно и другие посмотреть. Don't reinvent a wheel :)

2019-08-11 13:12 UTC, eignatik commented
👍 Kudos for RegEx usages 😄

2019-08-11 13:13 UTC, eignatik commented
⚠️ **Pay attention to Sonar**: https://sonarcloud.io/project/issues?id=eignatik_petpool-ui&pullRequest=14&resolved=false&types=CODE_SMELL

2019-08-13 14:46 UTC, githelga commented
Замечания исправлены
Добавила проверку уникальности логина и почты (будет работать с веткой feature/checkUsernamesAndEmails#47)

2019-08-13 15:05 UTC, eignatik requested changes

2019-08-13 15:05 UTC, eignatik commented on src/components/signup/SignUp.js
>       let updatedObject = this.getInnerErrors();
updatedObject - это что конкретно? Объект валидации? Стоит найти более понятное имя для переменной.

2019-08-13 15:05 UTC, eignatik commented on src/components/signup/SignUp.js
> +  handleChange(event, object) {
все еще непонятно, о каком объекте речь - если этот объект - реузльтат отправленный формы, то стоит его назвать соответсвующе

2019-08-13 15:05 UTC, eignatik commented on src/components/signup/SignUp.js
> +      ValidationUtil.checkElementIsTooShort(this.state.person.userName, 3), ValidationUtil.checkElementIsTooLong(this.state.person.userName, 20),
Magic numbers are not allowed. Please, move it to dedicated constants. https://codeburst.io/software-anti-patterns-magic-numbers-7bc484f40544

2019-08-13 15:05 UTC, eignatik commented on src/util/ValidationUtil.js
> +    return value != null && value.length > 2
Давай зададим минимальное число символов для user name = 6 (соответсвенно, вынесем это так же в константу)

2019-08-13 15:05 UTC, eignatik commented on src/util/ValidationUtil.js
> +    return value == null || value.length === 0;
No need to check all the conditions. It's enough only to cast `value` to boolean 
` ... return !!value `
**************
You can just check if the variable has a truthy value or not. That means
```
if( value ) {
}
```
will evaluate to true if value is not:

1. null
1 .undefined
1. NaN
1. empty string ("")
1. 0
1. false

The above list represents all possible false values in ECMA-/Javascript. Find it in the specification at the `ToBoolean` [section](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-262.pdf).

2019-08-13 16:00 UTC, githelga commented
Поправила
Добавила проверку на валидность email

2019-08-18 18:54 UTC, eignatik commented
У email нужно добавить проверку части до @, чтобы не было возможности ввести email вида @@test.ru (сейчас он считается валидным).

![telegram-cloud-photo-size-2-5390906679673072516-x](https://user-images.githubusercontent.com/17726963/63228905-51cec180-c1fa-11e9-927f-91221f5a82df.jpg)


разрешенные символы в email имени:
> The local-part of the email address may use any of these ASCII characters:
> 
> uppercase and lowercase Latin letters A to Z and a to z;
> digits 0 to 9;
> special characters !#$%&'*+-/=?^_`{|}~;
> dot ., provided that it is not the first or last character unless quoted, and provided also that it does not appear consecutively unless quoted (e.g. John..Doe@example.com is not allowed but "John..Doe"@example.com is allowed);
> space and "(),:;<>@[\] characters are allowed with restrictions (they are only allowed inside a quoted string, as described in the paragraph below, and in addition, a backslash or double-quote must be preceded by a backslash);
> comments are allowed with parentheses at either end of the local-part; e.g. john.smith(comment)@example.com and (comment)john.smith@example.com are both equivalent to john.smith@example.com.

2019-08-18 19:00 UTC, eignatik requested changes
Please, add an additional validation for the email

2019-08-21 18:47 UTC, eignatik submitted a review, later dismissed

2019-08-22 13:18 UTC, githelga commented
Done

2019-08-25 07:53 UTC, eignatik approved these changes

2019-08-25 14:41 UTC, merged